name = "flickrgroupaddr-oauth-callback"
type = "javascript"
zone_id = ""
account_id = ""
route = "auth.flickrgroupaddr.com/oauth/callback*"
workers_dev = false
compatibility_date = "2021-12-03"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
